### ISSUE TITLE
Nothin happened

### ISSUE THREAD

**Issue by zemocode** [TheTrain2000/async2rewrite#18]
I installed the async2rewrite but it didn't work. I also done the file convert and still nothing

**Comment by tylergibbs2** [comment]
If there's no errors and nothing printed to console, that means async2rewrite completed the conversion successfully. The converted files will have the original file name with `.a2r.py` added to the end. If you can't find them in the same directory as the original files, [check the directory you ran the module in.](https://i.imgur.com/QH7Lkj3.png)
