### ISSUE TITLE
I can't install the module

### ISSUE THREAD

**Issue by Supersebi3** [TheTrain2000/async2rewrite#3]
I'm trying to install the module using the android app **Termux**. I get this error message: ```unable to execute 'arm-linux-androideabi-clang': No such file or directory    error: command 'arm-linux-androideabi-clang' failed with exit status 1    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-p4gilwlc/typed-ast/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-39_jjk1r-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-p4gilwlc/typed-ast/``` 

The command I used to install it was `python -m pip install -U async2rewrite`, but just typing `pip install async2rewrite` gives the same problem.

**Comment by tylergibbs2** [comment]
This library does not officially support Termux, so I cannot help you with this as I am unfamiliar with it.

**Comment by Supersebi3** [comment]
Termux is just a normal linux terminal for android, so it should work normally

**Comment by tylergibbs2** [comment]
@Supersebi3 Again, I do not officially support this, but this might help: https://github.com/kivy/python-for-android/issues/78
